### ISSUE TITLE
3D Inference

### ISSUE THREAD

**Issue by RomStriker** [lemoshu/MTCL#2]
Hi,

I was wondering, during inference, why did you choose to perform 2D inference instead of 3D? While reading the Methods section of the paper, it seems like the training is done using 3D volumes. Are you going to provide an implementation for 3D inference in the near future?

**Comment by lemoshu** [comment]
Hi,

-We mention that we use the 2D version for both training and inference in this paper (see experiment section/comparison study). We found that 3D Net performed worse in our exploratory fully-supervised setting (for this task).  
-Yes. We are going to extend this paper, and may add experiments with 3D U-Net. I think it is also feasible for you to adapt it by yourself. All the implementation is on top of the github project "SSL4MIS", you can refer to the 3D Net implementation (fully-supervised, MT, etc) and quickly adapt the CL module inside.

**Comment by RomStriker** [comment]
Thanks. I missed the part where you mentioned the 3D performance. I will try to adapt it myself.
