### ISSUE TITLE
About the dataset for training process

### ISSUE THREAD

**Issue by muxin0527** [lemoshu/MTCL#5]
For the training process(Semi-supervised learning), how to allocate 3Dircadb and MSD8 dataset in folder?

**Comment by lemoshu** [comment]
Hi,

First, just follow the common SSL preparation: put the training slices of ircad and msd8 into one folder. Then, generate the training slice list. Distinct from common SSL, we should put the ircad slices at the top of the list (e.g., if I preprocessed 1298 ircad slices for training, 1~1298 slices are for ircad), and msd slices are placed after the ircad, i.e., 1298 to end. We denote the msd slices as unlabeled idxs in the training script:

    labeled_idxs = list(range(0, labeled_slice))    # for ircadb
    unlabeled_idxs = list(range(labeled_slice, total_slices))   # for msd
