### ISSUE TITLE
Request for preprocessed data

### ISSUE THREAD

**Issue by pleaseconnectwifi** [lemoshu/MTCL#7]
Thank you for your fantastic work of 'Anti-interference from Noisy Labels: Mean-Teacher-assisted Confident Learning for Medical Image Segmentation' on TMI!

Could you please share with me the **preprocessed data** for your experiment? For example the preprocessed left atrium (LA) segmentation dataset, or the real-world hepatic vessel segmentation datasets, or the real-world retinal vessel segmentation datasets? We are going to do some testing and **just one of them** will be OK~

I would very much appreciate your help and looking forward to your reply!

**Comment by lemoshu** [comment]
Hi Shuquan,

Just check the mailbox. Also, check our updated 3D version!
